### PR TITLE
Create interaction handle during animation

### PR DESCRIPTION
**Pull request by Jyrno42**
This makes the path animation compatible with InteractionManager.runAfterInteractions

see https://facebook.github.io/react-native/docs/interactionmanager

### CODE REVIEW

**Comment by Jyrno42** [comment]
Note: The tests failure seems to be unrelated to my changes.

**Comment by Jyrno42** [comment]
I tested it manually and the regular functionality still worked. It generally won't make any difference in performance, unless the consumers use InteractionManager.runAfterInteractions. 

In the app I am building I have a display type toggle. Tapping on it changes the rendered chart values and also notifies other component that the display type changed. The animation for the chart is smoother when I move the notification code into InteractionManager.runAfterInteractions.

**Comment by Jyrno42** [comment]
For example, built-in Animated methods create

**Comment by Jyrno42** [comment]
Accidentally pressed close

**Comment by Jyrno42** [comment]
@JesperLekland Let me know if this needs something more to get it merged.

**Comment by JesperLekland** [comment]
Great job, I'll merge and try to get it released this weekend 👍

**Comment by Jyrno42** [comment]
Hey @JesperLekland, not to rush you or anything, but could you please do the release?

**Pull request merged**
