### PR TITLE
Corner Radius to BarChart and StackedBarChart

### PR DESCRIPTION
**Pull request by nthegedus**
As I've found here [https://github.com/JesperLekland/react-native-svg-charts/issues/48](url) is not possible round corners until now.

This is how I imagine
captura de tela 2018-04-03 as 10 51 36

### CODE REVIEW

**Comment by JesperLekland** [comment]
what is this PR (impossible to tell from the changes)? And how have you managed to submit a PR from dev and not a fork? All PRs should be made against dev

**Comment by JesperLekland** [comment]
Closing as this is simply a PR from dev to master

**Comment by LRNZ09** [comment]
How it has been resolved? I cannot find any `cornerRadius` reference.

**Comment by JesperLekland** [comment]
It hasn't been resolved, nor was this a PR that aimed to resolve it

**Comment by LRNZ09** [comment]
Okay thanks! So at the moment there's no way to do round corners on bars?

**Comment by JesperLekland** [comment]
Correct, at the moment the bars are svg paths, i.e no way to specifically set any border radii

**Pull request closed without merging**
