### PR TITLE
Rename a component from `.ios.js` to `.js`

### PR DESCRIPTION
**Pull request by ahmedlhanafy**
This library works flawlessly for me with `react-native-web`. 

The only problem I have is that this file `horizontal-labeled-bar-chart-component.ios.js` can't be resolved in the web context. 

Renaming this file from `.ios.js` to `.js` breaks nothing on the iOS side, however, it fixes the web build.

### CODE REVIEW

**Comment by JesperLekland** [comment]
I think this is on your webpack end, `react-native-web` should handle `*.ios.js` files according to their documentation.

**Comment by JesperLekland** [comment]
closing due to inactivity

**Comment by JesperLekland** [comment]
The files mentioned in this PR is no longer included in the library. There is one [open issue](https://github.com/JesperLekland/react-native-svg-charts/issues/50) regarding react-native-web

**Comment by AlexBrasileiro** [comment]
@JesperLekland thank you o/

**Pull request closed without merging**
