### PR TITLE
Clone React element only if child is not `null`

### PR DESCRIPTION
**Pull request by attitude**
Fixes case for adding children of the chart with confition, e.g. when
`showGrid` is false JSX passes a `null` child:

```
const Graph = ({ showGrid }) => {
  const { showGrid } = props

  return (
    <AreaChart
      style={{ height: 200 }}
      data={ data }
      contentInset={{ top: 30, bottom: 30 }}
      curve={ shape.curveNatural }
      svg={{ fill: 'rgba(134, 65, 244, 0.8)' }}
    >
      {showGrid && <Grid/>}
    </AreaChart>
  )
}
```

### CODE REVIEW

**Comment by JesperLekland** [comment]
Hi @attitude and thanks for your contribution! Good catch, what behaviour do you experience currently, a crash? This fix should be applied to the rest of the charts and axes as well

**Comment by attitude** [comment]
@JesperLekland, I got red screen while trying a Area graph so I assume this would cause app to crash. I updated the PR with fixes of other occurences.

**Comment by JesperLekland** [comment]
Great @attitude! I noticed you've made the PR against `master`, the PR should be against `dev`. If you could branch of off dev instead that we be awesome 👍 Trying to keep `master` a copy of the current npm release.

**Comment by attitude** [comment]
Right, I see... lots of conflicts. I'll close this PR, branch from `development` and recreate the fixes and create a new PR.

PS: Just an idea: I guess there's an option to set default branch to development. I guess that should check out development by default and help others in the future.

**Comment by JesperLekland** [comment]
@attitude You are correct about that option, the problem is that people will see the `dev` code when browsing the files, which is not the code they will have when installing from npm.

**Pull request closed without merging**
