### PR TITLE
multiline support

### PR DESCRIPTION
**Pull request by abtuhin**
Added two files for supporting multiple line

### CODE REVIEW

**Comment by JesperLekland** [comment]
Hi @abtuhin and thank you for your contribution. 

Please work off of dev, master is meant to reflect what is published to npm

**Comment by abtuhin** [comment]
I am new in contributing to any public repository, will do it accordingly, thanks.
This package helped me a lot.

**Comment by JesperLekland** [comment]
@abtuhin Then welcome to the open source world 🙂
Make sure you read the [contribution guidelines](https://github.com/JesperLekland/react-native-svg-charts/blob/master/CONTRIBUTING.md)

After a quick look at your PR I think you can do the same without introducing new components. Have a look at the BarChart and how that handles multiple data sets

**Comment by abtuhin** [comment]
I was searching for multiple line on a single chart and thought it would be better to create separate component that only support 2D datasets for multiple line, although it was possible not cloning and modifying chart.js rather tweaking a bit. 
Thanks for your reply, I will try to update my
PR for your further review and let me know if this is a bit necessary to plot multi line in a single chart through a separate component.

**Comment by JesperLekland** [comment]
Closing this due to inactivity. Feel free to reopen

**Comment by GSreact** [comment]
Can you help me with a simple example of a multi-line graph implementation?
Thank you very much

**Comment by abtuhin** [comment]
I came up with a solution by adding two more files. multiline-chart.js and MultiLineComponent.js. 

**# multiline-chart.js**

`import * as array from "d3-array";
import * as scale from "d3-scale";
import * as shape from "d3-shape";
import PropTypes from "prop-types";
import React, { PureComponent } from "react";
import { View } from "react-native";
import Svg from "react-native-svg";
import Path from "./animated-path";
import Grid from "./grid";

class MultiLineChart extends PureComponent {
	state = {
		width: 0,
		height: 0
	};

	_onLayout(event) {
		const { nativeEvent: { layout: { height, width } } } = event;
		this.setState({ height, width });
	}

	render() {
		const {
			data,
			xAccessor,
			yAccessor,
			yScale,
			xScale,
			style,
			createPaths,
			animate,
			animationDuration,
			showGrid,
			numberOfTicks,
			contentInset: { top = 0, bottom = 0, left = 0, right = 0 },
			gridMax,
			gridMin,
			renderDecorator,
			extras,
			gridProps,
			svg,
			renderGrid = Grid
		} = this.props;
		const { width, height } = this.state;

		if (data.length === 0) {
			return <View style={style} />;
		}
		const myMap = [];

		data.map((lines, i) => {
			let arr = [];
			lines.map((item, index) => {
				let tmp = {};
				tmp = {
					x: xAccessor({ lines, index }),
					y: yAccessor({ item, index })
				};
				arr.push(tmp);
			});
			myMap.push(arr);
		});

		let yValues = [];
		myMap.map(item => {
			item.map(val => yValues.push(val.y));
		});

		const xValues = myMap[0].map(item => item.x);
		const yExtent = array.extent([...yValues, 5, 50]);
		const xExtent = array.extent([...xValues]);

		const y = yScale()
			.domain(yExtent)
			.range([height - bottom, top]);

		const x = xScale()
			.domain(xExtent)
			.range([left, width - right]);

		const paths = createPaths({
			data: myMap,
			x,
			y
		});

		const ticks = y.ticks(numberOfTicks);

		const extraData = {
			x,
			y,
			width,
			height,
			...paths
		};
		return (
			<View style={style}>
				<View style={{ flex: 1 }} onLayout={event => this._onLayout(event)}>
					<Svg style={{ flex: 1 }}>
						{showGrid && renderGrid({ x, y, ticks, data, gridProps })}
						{paths.line.map((x, i) => {
							return (
								<Path
									key={i}
									fill={"none"}
									stroke={paths.color[i]}
									d={x}
									animate={animate}
									animationDuration={animationDuration}
								/>
							);
						})}

						{data.map((value, index) => renderDecorator({ x, y, value, index }))}
						{extras.map((item, index) => item({ ...extraData, index }))}
					</Svg>
				</View>
			</View>
		);
	}
}

MultiLineChart.propTypes = {
	// data: PropTypes.oneOfType([
	//     PropTypes.arrayOf(PropTypes.object),
	//     PropTypes.arrayOf(PropTypes.number),
	// ]).isRequired,
	svg: PropTypes.object,

	style: PropTypes.any,

	animate: PropTypes.bool,
	animationDuration: PropTypes.number,

	curve: PropTypes.func,
	contentInset: PropTypes.shape({
		top: PropTypes.number,
		left: PropTypes.number,
		right: PropTypes.number,
		bottom: PropTypes.number
	}),
	numberOfTicks: PropTypes.number,
	extras: PropTypes.arrayOf(PropTypes.func),

	renderDecorator: PropTypes.func,

	gridMin: PropTypes.number,
	gridMax: PropTypes.number,
	showGrid: PropTypes.bool,
	gridProps: PropTypes.object,
	renderGrid: PropTypes.func,

	xScale: PropTypes.func,
	yScale: PropTypes.func,

	xAccessor: PropTypes.func,
	yAccessor: PropTypes.func
};

MultiLineChart.defaultProps = {
	svg: {},
	width: 100,
	height: 100,
	curve: shape.curveLinear,
	contentInset: {},
	numberOfTicks: 10,
	showGrid: true,
	extras: [],
	xScale: scale.scaleLinear,
	yScale: scale.scaleLinear,
	xAccessor: ({ index }) => index,
	yAccessor: ({ item }) => item,
	renderDecorator: () => {}
};

export default MultiLineChart;
`
**# MultiLineComponent.js**

`import React from "react";
import * as shape from "d3-shape";
import MultiLineChart from "./multiline-chart";

class MultiLineComponent extends React.PureComponent {
	_createPaths = ({ data, x, y }) => {
		const { curve } = this.props;

		let path = "";
		let lines = [];
		data.map(item => {
			let line = shape
				.line()
				.x(d => x(d.x))
				.y(d => y(d.y))
				.defined(item => typeof item.y === "number")
				.curve(curve)(item);
			lines.push(line);
			path += line;
		});

		return {
			path: path,
			line: lines,
			color: this.props.colors
		};
	};

	render() {
		return <MultiLineChart createPaths={this._createPaths} {...this.props} />;
	}
}

MultiLineComponent.propTypes = {
	...MultiLineChart.propTypes
};

MultiLineComponent.defaultProps = {
	...MultiLineChart.defaultProps
};

export default MultiLineComponent;
`
And include MultiLineComponent in index.js 

`
...
import MultiLineChart from "./MultiLineComponent";

export {
        .....
	MultiLineChart,
}
`
@GSreact , hope this helps.
Thanks

**Pull request closed without merging**
