### PR TITLE
Release/3.0.0

### LINKED ISSUE #34: Any plans to support scaleTime
Do you have plans to support d3.scaleTime for time series data. Would be a useful addition to this very useful module.

### LINKED ISSUE #47: XAxis rotate labels
Due to the ordering of styles on labels, it is not possible to set transformations. They are overriden by the internals.

In our case we would like to rotate the text labels to have more space for its contents.

Have a look here:
https://github.com/JesperLekland/react-native-svg-charts/blob/7a9292431932dd01c66e09369cd2b745a9db536c/src/x-axis.js#L110

What do you think, would it make sense to reorder the attributes? Or at least to not return an empty array, but null / undefined. I think this would be than ignored and would only break transforms on PIE charts.

### PR DESCRIPTION
**Pull request by JesperLekland**
* Fixes #47 
* Fixes #34

### CODE REVIEW

**Comment by Amnesthesia** [comment]
Hell yeah! 

Could we get some more documentation/examples on the new x/y timescale props?

**Comment by JesperLekland** [comment]
@Amnesthesia I'm trying to figure out a way to not bloat the README to much, will probably be a lot better when I set up the showcase repository. For now you could just check the storybook examples, there is one story for the timescale :)

**Comment by Amnesthesia** [comment]
Jesus, it's insane how quick you reply.

But, fuck yeah that's great! Will do!

**Comment by JesperLekland** [comment]
Haha! Happy to help 😂

**Comment by Amnesthesia** [comment]
Does StackedAreaChart support `yAxisAccessor` and `xAxisAccessor`, and how would you return multiple values here? Would it be supported to have `undefined` values for some object (e.g like in the original example, where objects have different Y keys but share X axis)?

**Pull request merged**
