### PR TITLE
Added installation instructions in README.md

### PR DESCRIPTION
**Pull request by tapanprakasht**
Current README.md does not contain installation instruction for the library. Even though it is talking about prerequisites, installation instruction should be included in the README.md of a libraray.
This pull request contain necessary changes to add installation instruction for the same.

### CODE REVIEW

**Comment by JesperLekland** [comment]
Hi @tapanprakasht and thanks for your PR. 

This is a conscious choice. This library has no reason to maintain installation instructions for another library that has a perfectly good README, and is clearly linked in the `prerequisites` section. Including it here would also require us to maintain it.  Reading the `react-native-svg` README gives the user  much better insight into a vital component of this library and that shouldn't be skipped.

Thank you again for your contribution but this particular PR will not be merged.

**Comment by nwaughachukwuma** [comment]
Hi @JesperLekland, a simple yarn add react-native-svg-charts or npm install react-native-svg-charts --save would do.

**Comment by JesperLekland** [comment]
@nwaughachukwuma except it is not enough, the user *needs* to install, link and understand `react-native-svg` as well.

**Comment by nwaughachukwuma** [comment]
Exactly @lekland this is how it should be stated in the readme, to cater for not too experienced users. Importantly, add the installation command for this library and point users to react-native-svg as a prerequisite. Am open to doing a PR if it's fine by you.

Awesome library by the way.

**Comment by JesperLekland** [comment]
I'm conflicted about this. This is not a high level library, and certain prerequisites are on the user (for example how to install an npm package). Making it *too* easy to get going will most likely open up a flood of issues from inexperienced users (related or unrelated to this library), something we don't have the capacity to handle. 

Thanks for the support guys, open source is hard!

**Pull request closed without merging**
